server:
  port: 30156

star:
  plugin:
    app-name: spark-star
    master: yarn
    spark-config:
      spark.ui.port: 30157
      hive.metastore.uris: thrift://dcloud-dev:30123
      spark.driver.memory: 1g
      spark.executor.memory: 4g
      spark.sql.storeAssignmentPolicy: LEGACY
