spring:
  kafka:
    producer:
      bootstrap-servers: 39.103.230.188:30120
      client-id: spark-star-kafka
      key-serializer: StringSerializer.class
      value-serializer: StringSerializer.class