server:
    port: 8888

logging:
  level:
    star: debug
  group:
    star: com.isxcode.star

star:
  node:
    host: 8.142.31.232
    port: 30156
    key: star-key
    kafka-config:
      bootstrap.servers: 8.142.31.232:9092
      group.id: test-consumer-group
