server:
    port: 8888

logging:
  level:
    star: debug
  group:
    star: com.isxcode.star

star:
  node:
    host: 39.103.230.188
    port: 30156
    key: star-key
    kafka-config:
      bootstrap.servers: 39.103.230.188:30120
      group.id: test-consumer-group
