server:
    port: 8888

star:
  plugin:
    kafka-config:
      bootstrap.servers: 39.103.230.188:30120
      group.id: test-consumer-group
  node:
    host: 39.103.230.188
    port: 30156
    key: star-key
