server:
  port: 30156
  servlet:
    context-path: /spark-star

logging:
  group:
    star: com.isxcode.star
  level:
    star: debug

star:
  plugin:
    server-key: star-key
    master: yarn
    kafka-config:
      bootstrap.servers: 39.103.230.188:30120
      topic: star-topic
      replication.factor: 1
      partitions: 1
