server:
  port: 30156
  servlet:
    context-path: /spark-star

logging:
  group:
    star: com.isxcode.star
  level:
    star: debug

star:
  plugin:
    server-key: star-key
    app-name-prefix: spark-star
    master: yarn
    spark-config:
      spark.ui.port: 30128
      spark.executor.memory: 4g
      spark.executor.cores: 1
      spark.driver.memory: 1g
      spark.num.executors: 1
      hive.metastore.uris: thrift://localhost:9083
