server:
  port: 30156
  servlet:
    context-path: /spark-star

logging:
  group:
    star: com.isxcode.star
  level:
    star: debug

star:
  plugin:
    server-key: star-key
    app-name-prefix: spark-star
    master: yarn
    properties-file: /home/dehoop/spark-star/star/conf/executor.conf
    kafka-config:
      bootstrap.servers: 39.103.230.188:30120
      topic: star-topic
      replication.factor: 1
      partitions: 1
    spark-config:
      spark.executor.memory: 4g
      spark.executor.cores: 1
      spark.driver.memory: 1g
      spark.num.executors: 1
